<script>

Ext.onReady(function() {

    var myview = Ext.create('App.view.Viewport');

    var myform = Ext.create('Ext.container.Container', {
                        id:'panellogin',
                        layout: 'fit',
                        whith: '100%',
                        style: {
                            background : '#ffffff !important'
                        },
                        items:[
                            {
                                xtype: 'form',
                                id:'formlogin',
                                title: 'Login',
                                frame: true,
                                bodyPadding: 10,
                                margin :'20 20 20 20',
                                defaultType: 'textfield',
                                items:[
                                    {
                                        // xtype: 'textfield',
                                        allowBlank: false,
                                        fieldLabel: 'Usuário',
                                        id: 'user',
                                        name: 'user',
                                        emptyText: 'Usuário'
                                    }, 
                                    {
                                        // xtype: 'textfield',
                                        allowBlank: false,
                                        fieldLabel: 'Senha',
                                        id: 'pass',
                                        name: 'pass',
                                        emptyText: 'Senha',
                                        inputType: 'password'
                                    }
                                ],

                                buttons: [
                                    { 
                                        text: 'Login',
                                        handler: function() {

                                            var user = this.up('form').down('#user').getValue();
                                            var pass = this.up('form').down('#pass').getValue();

                                            params = {
                                                    user: user,
                                                    pass: pass
                                                };

                                            Ext.MessageBox.show({
                                                msg: 'Verificando a permissão de acesso...',
                                                progressText: 'Saving...',
                                                width: 300,
                                                wait: {
                                                    interval: 200
                                                }
                                            });
                                            
                                            Ext.Ajax.request({
                                                url: BASEURL +'/api/Index/logar',
                                                method: 'POST',
                                                params: params,
                                                success: function (response) {

                                                    Ext.MessageBox.hide();
                                                    var result = Ext.decode(response.responseText);

                                                    if(!result.success){
                                                        new Noty({
                                                            theme: 'relax',
                                                            layout: 'bottomRight',
                                                            type: 'error',
                                                            closeWith: [],
                                                            text: 'Acesso negado. '+result.msg
                                                        }).show();
                                                    }else{
                                                        window.location.href = BASEURL + '/';
                                                    }
                                                }
                                            });
                                        }
                                    }
                                ],

                                defaults: {
                                    anchor: '100%',
                                    labelWidth: 120
                                }

                            }
                        ]
                });

        var pMsg = Ext.MessageBox.show({
            msg: 'Verificando a permissão de acesso...',
            progressText: 'Saving...',
            width: 300,
            wait: {
                interval: 200
            }
        });

        Ext.Ajax.request({
            url: BASEURL +'/api/index/login',
            method: 'POST',
            success: function (response) {
                var result = Ext.decode(response.responseText);
                Ext.MessageBox.hide();
                
                if(!result.success){
                    
                    myview.add(myform);
                }

                if(result.success){
                    window.location.href = BASEURL + '/';
                }
            }
        });
});
</script>